### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by FranklinYu** [mde/ejs-site#12]
If I understand correctly this is the repository for http://ejs.co/ right?

Any opinion about making it https://ejs.co/ with HTTPS/SSL/TLS? Chrome begins to flag sites “insecure” with plain HTTP. Nowadays it doesn’t cost much money (if any) to host an HTTPS site. Is there anything I can help?

**Comment by mde** [comment]
I've got us set up with CloudFlare. We should see a change as soon as DNS server changes propagate.

**Comment by mde** [comment]
Looks like we're active on CloudFlare: https://ejs.co/ I've got "force SSL" turned on, so people with the old scheme should be redirected to HTTPS. Thanks for filing this!
