### ISSUE TITLE
Few typos on the site

### ISSUE THREAD

**Issue by vivekmore** [mde/ejs-site#4]
1. I think it should say **Custom delimiters** instead of **Customer delimiters**
2. I think the year in the footer was meant to be 2012 _unless you're from the future ;-)_

**Comment by mde** [comment]
Thank you! I have fixed the typo.

The copyright date is a bit of a joke -- it's from one of my favorite Rush albums: https://en.wikipedia.org/wiki/2112_%28album%29

I built a framework for Node named after their bass player, and I just started using it everywhere. :)

**Comment by vivekmore** [comment]
Lol!
