### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by RyanZim** [mde/ejs-site#6]
@mde: As is pretty obvious from looking at the source code, there isn't much standardization in the coding style of the HTML. I would be willing to straighten out some of the oddities, but I'm not sure what coding style you prefer.

---

Here's my personal preferences for HTML:
- 4 spaces indent
- `<p>` tags on same line
  
  ```
  <p>Hello World!</p>
  ```
- `<li>` on same line if the line is short, block-style for longer points
  
  ```
  <li>Point one</li>
  
  <li>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Nunc mauris turpis, congue vestibulum fringilla quis, porta ac ipsum. 
      Suspendisse sollicitudin iaculis felis vel sollicitudin. 
      Quisque tempus tristique turpis eget vestibulum.
  </li>
  ```

Let me know what you think of this style. I won't start work until I know your preference.

**Comment by TimothyGu** [comment]
> - 4 spaces indent

Meh; I'd prefer 2 spaces, just to be consistent with JavaScript. It's also much easier to have a very high level of indentation in HTML than in JS, making 4 spaces a little clumsy.

Also, why two different styles for `<p>` and `<li>`?

**Comment by RyanZim** [comment]
Just personal preference. I never liked the looks of:

```
<p>
    Hello World!
</p>
```

For the same reason, I don't like:

```
<li>
    Hello World!
</li>
```

However, when you have a `br` tag or `code` block inside a list, putting `<li>` on the same line is unreadable IMO. Sorry, my example was a bit lame.

Here is a better example for block-style `<li>` (from this page's source code):

```
<li>
    <p><code>&lt;p&gt;</code> tags on same line</p>
    <pre><code>&lt;p&gt;Hello World!&lt;/p&gt;
    </code></pre>
</li>
```

**Comment by TimothyGu** [comment]
That's fair, but not what I was asking. What about

``` html
<p>
  A very meaningful paragraph with a
  <img src="" alt="picture">
  amongst the text.
</p>
```

**Comment by RyanZim** [comment]
I almost never put an `<img>` inside a `<p>`, so I never thought about that. If there would be a complex case with `<p>`, I wouldn't be opposed; I just don't like seeing block-style `p`'s constantly.

**Comment by mde** [comment]
Let's go with two-space indent.

Also, let's generally say that block-level elements like p, div, li, all go on the same line if the content is one line. If it's multi-line, the tags go on their own line.

**Comment by RyanZim** [comment]
OK, I'll try to get a PR ready soon. Will probably add an .editorconfig file as well.
